// products list actions
export const FETCH_ALL_PRODUCTS_START = 'FETCH_ALL_PRODUCTS_START';
export const FETCH_ALL_PRODUCTS_SUCCESS = 'FETCH_ALL_PRODUCTS_SUCCESS';
export const FETCH_ALL_PRODUCTS_FAILED = 'FETCH_ALL_PRODUCTS_FAILED';

// product cart actions
export const FETCH_PRODUCT_BY_ID_START = 'FETCH_PRODUCT_BY_ID_START';
export const FETCH_PRODUCT_BY_ID_SUCCESS = 'FETCH_PRODUCT_BY_ID_SUCCESS';
export const FETCH_PRODUCT_BY_ID_ERROR = 'FETCH_PRODUCT_BY_ID_ERROR';



