// products list actions
export const FETCH_ALL_PRODUCTS_START = 'FETCH_ALL_PRODUCTS_START';
export const FETCH_ALL_PRODUCTS_SUCCESS = 'FETCH_ALL_PRODUCTS_SUCCESS';
export const FETCH_ALL_PRODUCTS_ERROR = 'FETCH_ALL_PRODUCTS_ERROR';
export const FETCH_PRODUCT_BY_ID_START = 'FETCH_PRODUCT_BY_ID_START';
export const FETCH_PRODUCT_BY_ID_SUCCESS = 'FETCH_PRODUCT_BY_ID_SUCCESS';
export const FETCH_PRODUCT_BY_ID_ERROR = 'FETCH_PRODUCT_BY_ID_ERROR';

// product cart actions
export const ADD_PRODUCT_TO_BASKET_SUCCESS = 'ADD_PRODUCT_TO_BASKET_SUCCESS';
export const ADD_PRODUCT_TO_BASKET_ERROR = 'ADD_PRODUCT_TO_BASKET_ERROR';
export const DECREASE_PRODUCT_QUANTITY = 'DECREASE_PRODUCT_QUANTITY';
export const INCREASE_PRODUCT_QUANTITY = 'INCREASE_PRODUCT_QUANTITY';
export const SET_SEARCH = 'SET_SEARCH';
export const REMOVE_SEARCH = 'REMOVE_SEARCH';
export const SET_USER = 'SET_USER';
export const RESET_STATE = 'RESET_STATE';
